name: MLflow Project CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8

      - name: Install MLflow
        run: pip install mlflow

      - name: Run MLflow Project
        run: |
          cd Workflow-CI/MLProject
          mlflow run .

      - name: Upload model artifacts
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: Workflow-CI/MLProject/mlruns/**/artifacts/model/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get latest MLflow run ID
        id: get_run_id
        run: |
          cd Workflow-CI/MLProject/mlruns/0
          RUN_ID=$(ls -td -- */ | head -n1 | tr -d '/')
          echo "Latest RUN_ID: $RUN_ID"
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      - name: Build MLflow Docker image
        run: |
          cd Workflow-CI/MLProject
          mlflow models build-docker -m ./mlruns/0/${{ steps.get_run_id.outputs.run_id }}/artifacts/model -n ulfasyabania173/california-housing-mlflow:${{ steps.get_run_id.outputs.run_id }}

      - name: List Docker images
        run: docker images

      - name: Push Docker image        run: docker push ulfasyabania173/california-housing-mlflow:${{ steps.get_run_id.outputs.run_id }}